Update 5-authentication.md
The earlier version of this code was not following the pattern being used throughout the tutorial and returning the following error due to the context argument not containing a `db` property.
```
TypeError: Cannot read property 'mutation' of undefined`
```

This change follows the pattern used throughout the tutorial and I've tested to ensure its writing the correct user information into the post record.